### PR TITLE
Create Prince browser

### PR DESCRIPTION
**Pull request by jitdummy**
wsg

### CODE REVIEW

**Comment by jitdummy** [comment]
yo i cannot remix this?

**Comment by owokoyo** [comment]
@jitdummy You may but your changes will not be merged into upstream

**Comment by jitdummy** [comment]
mk i was wondering would u like to maek a new code.org script
where like u can do other stuff that no one has

**Comment by jitdummy** [comment]
would that be cool?

**Comment by owokoyo** [comment]
no

**Comment by owokoyo** [comment]
(Accidentally reopened)

**Comment by jitdummy** [comment]
how do i get it to say my name on the opening Screen

**Comment by jitdummy** [comment]
so what scripts can u make?

**Comment by owokoyo** [comment]
As a rule of thumb for any project you did not make you should not try to take credit from its original author, but the source for the main page is located in pages/index.tsx

I do not make any scripts, not ones that would be useful to you anyways..

**Comment by jitdummy** [comment]
im not i was gonna put Remixed from the your link to your acc

**Comment by jitdummy** [comment]
ok could u teach me how to make my own script?

**Comment by jitdummy** [comment]
if its ok?

**Comment by owokoyo** [comment]
I am not ready for that kind of investment of my time. This project will always remain open source if you would like to understand the underlying "technology." In my personal opinion I would you gain a solid grasp of node.js before attempting this type of thing.

**Comment by jitdummy** [comment]
mmk

**Pull request closed without merging**
